# SPDX-License-Identifier: MIT
---
- name: Find the first unpartitioned disk
  ansible.builtin.shell: |
    set -o pipefail
    lsblk -n -o NAME,TYPE,PKNAME | awk '
      $2=="disk" && $1 !~ /^zram|^loop|^dm/ { disk=$1; haspart[disk]=0 }
      $2=="part" { parent=$3; if (parent in haspart) haspart[parent]=1 }
      END {
        for (d in haspart) {
          if (haspart[d] == 0) {
            print d
            exit 0
          }
        }
      }
    '
  register: __trustee_client_unpartitioned_disk
  changed_when: false
  failed_when: false

- name: Encrypt disk
  when: __trustee_client_unpartitioned_disk.stdout != ""
  vars:
    __trustee_client_disk_device: "/dev/{{ __trustee_client_unpartitioned_disk.stdout }}"
    __trustee_client_disk_partition: >-
      /dev/{{ __trustee_client_unpartitioned_disk.stdout }}{{ 'p' if 'nvme' in __trustee_client_unpartitioned_disk.stdout else '' }}1
  block:
    - name: Ensure packages for disk encryption are installed
      ansible.builtin.package:
        name: "{{ __trustee_client_encrypt_disk_packages }}"
        state: present
        use: "{{ (__trustee_client_is_ostree | d(false)) |
              ternary('ansible.posix.rhel_rpm_ostree', omit) }}"

    - name: Create temporary file for disk encryption key
      ansible.builtin.tempfile:
        state: file
        suffix: .bin
      register: __trustee_client_secret_key_tempfile

    - name: Acquire disk encryption key from Secret Registration Client service
      ansible.builtin.shell: |
        /usr/local/bin/secret_registration_client.sh --fetch-key-to {{ __trustee_client_secret_key_tempfile.path }}
      changed_when: true
      no_log: true

    - name: Encrypt the partition
      ansible.builtin.shell: |
        set -o pipefail
        parted -s {{ __trustee_client_disk_device }} mklabel gpt
        parted -s {{ __trustee_client_disk_device }} mkpart primary ext4 0% 100%
        cryptsetup luksFormat --key-file {{ __trustee_client_secret_key_tempfile.path }} --batch-mode {{ __trustee_client_disk_partition }}
        cryptsetup open --key-file {{ __trustee_client_secret_key_tempfile.path }} {{ __trustee_client_disk_partition }} encrypted-disk
        mkfs.ext4 /dev/mapper/encrypted-disk
        [ -d {{ trustee_client_encrypt_disk_mount_point }} ] || mkdir -p {{ trustee_client_encrypt_disk_mount_point }}
        mount /dev/mapper/encrypted-disk {{ trustee_client_encrypt_disk_mount_point }}
      changed_when: true
      no_log: true

    - name: Clean up disk encryption key file
      ansible.builtin.file:
        path: "{{ __trustee_client_secret_key_tempfile.path }}"
        state: absent
