# SPDX-License-Identifier: MIT
---
- name: Find the firstunpartitioned disk
  shell: |
    lsblk -n -o NAME,TYPE,PKNAME | awk '
      $2=="disk" {disk=$1; haspart[disk]=0}
      $2=="part" {parent=$3; if (parent in haspart) haspart[parent]=1}
      END {
        for (d in haspart) {
          if (haspart[d] == 0) {
            print d
            exit 0
          }
        }
      }
    '
  register: unpartitioned_disk
  changed_when: false
  failed_when: false

- name: Encrypt disk
  block:
    - name: Set fact with disk device path
      set_fact:
        disk_device: "/dev/{{ unpartitioned_disk.stdout }}"

    - name: Create partition table and partition on disk
      shell: |
        parted -s {{ disk_device }} mklabel gpt
        parted -s {{ disk_device }} mkpart primary 0% 100%

    - name: Generate a key and encrypt the partition
      shell: |
        head -c 32 /dev/urandom | base64 > /tmp/key
        cryptsetup luksFormat --key-file /tmp/key --batch-mode {{ disk_device }}1
        cryptsetup open --key-file /tmp/key {{ disk_device }}1 encrypted-disk
        mkfs.ext4 /dev/mapper/encrypted-disk
        [ -d {{ cvm_deploy_encrypt_disk_mount_point }} ] || mkdir -p {{ cvm_deploy_encrypt_disk_mount_point }}
        mount /dev/mapper/encrypted-disk {{ cvm_deploy_encrypt_disk_mount_point }}

    - name: Read key from remote host
      slurp:
        src: /tmp/key
      register: slurped_key

    - name: Set encrypted disk key fact
      set_fact:
        encrypted_disk_key: "{{ slurped_key.content}}"

    - name: Clean up temporary key file
      file:
        path: /tmp/key
        state: absent
  when: unpartitioned_disk.stdout != ""

# TODO: Add a systemd service to mount the encrypted disk at boot