# SPDX-License-Identifier: MIT
---
- name: Deploy Trustee Server Components using Podman Quadlets from GitHub repository
  hosts: all
  vars:
    trustee_server_trustee: true
    trustee_server_quadlet_repo_url: "https://github.com/litian1992/trustee-quadlet-rhel.git"
    trustee_server_quadlet_repo_path: "quadlet"
    trustee_server_quadlet_repo_branch: "main"
    trustee_server_quadlet_install_dir: "/etc/containers/systemd"
    trustee_server_secret_registration_service_enabled: false
  roles:
    - linux-system-roles.trustee-server
